# https://redwoodjs.com/docs/app-configuration-redwood-toml
# Custom graphql & dbauth urls individually: https://redwoodjs.com/docs/app-configuration-redwood-toml#api-paths

[web]
  title = "${DISPLAY_URL} | ${TAGLINE_DESC}"
  port = 8910
  apiUrl = "/.netlify/functions"
  includeEnvironmentVariables = [
    "DISPLAY_URL",
    "TAGLINE_DESC",
    "DEV_URL",
    "ADMIN_EMAIL"
  ] # any ENV vars that should be available to the web side, see https://redwoodjs.com/docs/environment-variables#web
[api]
  port = 8911
[browser]
  open = false
